#langchain4j相关模型配置：
langchain4j:
  openai:
    chat-model:
      model-name: "qwen3.5-plus"
      api-key: ${DASHSCOPE_API_KEY}
      base-url: https://dashscope.aliyuncs.com/compatible-mode/v1
      max-tokens: 8192
      #json 格式输出配置
      response_format: json_object
      #开启日志
      logRequests: true
      logResponses: true

    streaming-chat-model:
      model-name: "qwen3.5-plus"
      api-key: ${DASHSCOPE_API_KEY}
      base-url: https://dashscope.aliyuncs.com/compatible-mode/v1
      logRequests: true
      logResponses: true
      max-tokens: 8192
    reasoning-streaming-chat-model:
      model-name: "qwen3.5-plus"
      api-key: ${DASHSCOPE_API_KEY}
      base-url: https://dashscope.aliyuncs.com/compatible-mode/v1
      logRequests: true
      logResponses: true
      max-tokens: 8192